name: UAT Deployment Tests

on:
  pull_request:
    branches: "*"

jobs:
  uat-test:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ">=3.12"

      - name: Checkout testing repository
        uses: actions/checkout@v4
        with:
          repository: felicityzhao9/aws-greengrass-testing
          ref: python_testing
          path: aws-greengrass-testing

      - name: Get temporary AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::832850273037:role/GGL-UAT-GH-Role
          role-duration-seconds: 1500
          unset-current-credentials: true

      - name: Run UAT tests
        run: |
          cd aws-greengrass-testing
          ./run-tests.sh \
            --aws-account=832850273037 \
            --s3-bucket=lite-uat-bucket \
            --commit-id=${{ github.event.pull_request.head.sha }} \
            --aws-region=us-west-2 \
            --test-category=deployment
